CREATE DATABASE IF NOT EXISTS fin_finder;

CREATE TABLE IF NOT EXISTS fishes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    longitude DECIMAL(4, 10) NOT NULL,
    attitude DECIMAL(4, 10) NOT NULL
);
